2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_setup.py:_flush():69] setting env: {}
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_104011-zu3w2zjn/logs/debug.log
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_104011-zu3w2zjn/logs/debug-internal.log
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_init.py:init():375] calling init triggers
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-29 10:40:11,684 INFO    MainThread:44483 [wandb_init.py:init():424] starting backend
2021-08-29 10:40:11,684 INFO    MainThread:44483 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-29 10:40:11,696 INFO    MainThread:44483 [backend.py:ensure_launched():135] starting backend process...
2021-08-29 10:40:11,703 INFO    MainThread:44483 [backend.py:ensure_launched():139] started backend process with pid: 44506
2021-08-29 10:40:11,704 INFO    MainThread:44483 [wandb_init.py:init():429] backend started and connected
2021-08-29 10:40:11,706 INFO    MainThread:44483 [wandb_init.py:init():477] updated telemetry
2021-08-29 10:40:11,706 INFO    MainThread:44483 [wandb_init.py:init():500] communicating current version
2021-08-29 10:40:12,456 INFO    MainThread:44483 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-29 10:40:12,456 INFO    MainThread:44483 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-29 10:40:12,681 INFO    MainThread:44483 [wandb_init.py:init():540] starting run threads in backend
2021-08-29 10:40:17,686 INFO    MainThread:44483 [wandb_run.py:_console_start():1584] atexit reg
2021-08-29 10:40:17,686 INFO    MainThread:44483 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-08-29 10:40:17,686 INFO    MainThread:44483 [wandb_run.py:_redirect():1463] Redirecting console.
2021-08-29 10:40:17,690 INFO    MainThread:44483 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-29 10:40:17,690 INFO    MainThread:44483 [wandb_init.py:init():565] run started, returning control to user process
2021-08-29 10:40:20,841 INFO    MainThread:44483 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-08-29 10:40:20,841 INFO    MainThread:44483 [wandb_run.py:_restore():1526] restore
2021-08-29 10:40:23,486 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:40:23,751 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:40:24,697 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 30042
}

2021-08-29 10:40:24,799 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 33042
}

2021-08-29 10:40:24,901 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 33042
}

2021-08-29 10:40:25,003 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6653
  total_bytes: 33042
}

2021-08-29 10:40:25,105 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,207 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,309 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,410 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,512 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,726 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:25,828 INFO    MainThread:44483 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 33042
  total_bytes: 33042
}

2021-08-29 10:40:26,958 INFO    MainThread:44483 [wandb_run.py:_show_files():1898] logging synced files
