2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_setup.py:_flush():69] setting env: {}
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_103632-1ugq6qdu/logs/debug.log
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_103632-1ugq6qdu/logs/debug-internal.log
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_init.py:init():375] calling init triggers
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-29 10:36:32,015 INFO    MainThread:43899 [wandb_init.py:init():424] starting backend
2021-08-29 10:36:32,015 INFO    MainThread:43899 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-29 10:36:32,027 INFO    MainThread:43899 [backend.py:ensure_launched():135] starting backend process...
2021-08-29 10:36:32,034 INFO    MainThread:43899 [backend.py:ensure_launched():139] started backend process with pid: 43922
2021-08-29 10:36:32,036 INFO    MainThread:43899 [wandb_init.py:init():429] backend started and connected
2021-08-29 10:36:32,037 INFO    MainThread:43899 [wandb_init.py:init():477] updated telemetry
2021-08-29 10:36:32,037 INFO    MainThread:43899 [wandb_init.py:init():500] communicating current version
2021-08-29 10:36:32,806 INFO    MainThread:43899 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-29 10:36:32,806 INFO    MainThread:43899 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-29 10:36:33,027 INFO    MainThread:43899 [wandb_init.py:init():540] starting run threads in backend
2021-08-29 10:36:38,033 INFO    MainThread:43899 [wandb_run.py:_console_start():1584] atexit reg
2021-08-29 10:36:38,033 INFO    MainThread:43899 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-08-29 10:36:38,033 INFO    MainThread:43899 [wandb_run.py:_redirect():1463] Redirecting console.
2021-08-29 10:36:38,038 INFO    MainThread:43899 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-29 10:36:38,038 INFO    MainThread:43899 [wandb_init.py:init():565] run started, returning control to user process
2021-08-29 10:36:41,233 INFO    MainThread:43899 [wandb_watch.py:watch():43] Watching
2021-08-29 10:36:42,645 INFO    MainThread:43899 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-08-29 10:36:42,646 INFO    MainThread:43899 [wandb_run.py:_restore():1526] restore
2021-08-29 10:36:45,128 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:36:45,364 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:36:46,052 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 8006
}

2021-08-29 10:36:46,156 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 11006
}

2021-08-29 10:36:46,261 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 11006
}

2021-08-29 10:36:46,363 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1288
  total_bytes: 11006
}

2021-08-29 10:36:46,466 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:46,568 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:46,670 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:46,772 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:46,873 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:47,294 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:47,396 INFO    MainThread:43899 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11006
  total_bytes: 11006
}

2021-08-29 10:36:48,514 INFO    MainThread:43899 [wandb_run.py:_show_files():1898] logging synced files
