2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_setup.py:_flush():69] setting env: {}
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_103349-1o0ipt22/logs/debug.log
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_103349-1o0ipt22/logs/debug-internal.log
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_init.py:init():375] calling init triggers
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-29 10:33:49,377 INFO    MainThread:43396 [wandb_init.py:init():424] starting backend
2021-08-29 10:33:49,377 INFO    MainThread:43396 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-29 10:33:49,389 INFO    MainThread:43396 [backend.py:ensure_launched():135] starting backend process...
2021-08-29 10:33:49,400 INFO    MainThread:43396 [backend.py:ensure_launched():139] started backend process with pid: 43416
2021-08-29 10:33:49,402 INFO    MainThread:43396 [wandb_init.py:init():429] backend started and connected
2021-08-29 10:33:49,403 INFO    MainThread:43396 [wandb_init.py:init():477] updated telemetry
2021-08-29 10:33:49,404 INFO    MainThread:43396 [wandb_init.py:init():500] communicating current version
2021-08-29 10:33:50,173 INFO    MainThread:43396 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-29 10:33:50,174 INFO    MainThread:43396 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-29 10:33:50,394 INFO    MainThread:43396 [wandb_init.py:init():540] starting run threads in backend
2021-08-29 10:33:55,398 INFO    MainThread:43396 [wandb_run.py:_console_start():1584] atexit reg
2021-08-29 10:33:55,399 INFO    MainThread:43396 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-08-29 10:33:55,399 INFO    MainThread:43396 [wandb_run.py:_redirect():1463] Redirecting console.
2021-08-29 10:33:55,402 INFO    MainThread:43396 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-29 10:33:55,403 INFO    MainThread:43396 [wandb_init.py:init():565] run started, returning control to user process
2021-08-29 10:33:58,561 INFO    MainThread:43396 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-08-29 10:33:58,561 INFO    MainThread:43396 [wandb_run.py:_restore():1526] restore
2021-08-29 10:34:00,955 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:34:01,243 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:34:01,413 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 7803
}

2021-08-29 10:34:01,515 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10803
}

2021-08-29 10:34:01,622 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10803
}

2021-08-29 10:34:01,724 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10803
}

2021-08-29 10:34:01,826 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:01,928 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:02,030 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:02,132 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:02,234 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:02,674 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:02,777 INFO    MainThread:43396 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10803
  total_bytes: 10803
}

2021-08-29 10:34:03,890 INFO    MainThread:43396 [wandb_run.py:_show_files():1898] logging synced files
